### ISSUE TITLE
Hunt for malicious use of Remote Access Tools

### ISSUE THREAD

**Issue by th3y3ti** [th3y3ti/festus6#1]
Hunt Name: <Hunt for xyz>
Hunt Description: <Brief description of what will be hunted for>
Trigger: <What triggered this hunt>

**Acceptance Criteria**  
This issue can be closed when the playbook has been updated and the report has been written. If the hunt can not be completed, this issue should be marked as blocked. If the issue is no longer needed, it should be labeled as such and then closed.

**Tasks**
- [x] Validate Security Gap Still Exists
- [x] Define/Refine Playbook
- [x] Validate Data Visibility/Usability 
- [x] Gather and Analyze Data According to the Playbook 
- [x] Automate Steps As You Can/Go
- [x] Update the Playbooks
- [x] Write Report
- [x] Share Findings
- [x] Close Issue

**Note:** Incidents should be escalated as they are found.

**Comment by th3y3ti** [comment]
- [ ]
