### ISSUE TITLE
Hunt for Web Shells

### ISSUE THREAD

**Issue by th3y3ti** [th3y3ti/festus6#3]
Hunt Name: Web Shells
Hunt Description: Hunt for webshells
Trigger: Historical Incident

**Acceptance Criteria**  
This issue can be closed when the playbook has been updated and the report has been written. If the hunt can not be completed, this issue should be marked as blocked. If the issue is no longer needed, it should be labeled as such and then closed.

**Tasks**
- [ ] Validate Security Gap Still Exists
- [ ] Define/Refine Playbook
- [ ] Validate Data Visibility/Usability 
- [ ] Gather and Analyze Data According to the Playbook 
- [ ] Automate Steps As You Can/Go
- [ ] Update the Playbooks
- [ ] Write Report
- [ ] Share Findings
- [ ] Close Issue

**Note:** Incidents should be escalated as they are found.
