### ISSUE TITLE
Hunt for bitsadmin abuse

### ISSUE THREAD

**Issue by th3y3ti** [th3y3ti/festus6#5]
Hunt Name: abuse of bitsadmin
Hunt Description: Hunt for bitsadmin being used to kick off suspicious processes, transfer data, etc
Trigger: Part Active Campaign Fuzzy Wuzzy

- https://attack.mitre.org/techniques/T1197/
- https://attack.mitre.org/techniques/T1048/

**Acceptance Criteria**  
This issue can be closed when the playbook has been updated and the report has been written. If the hunt can not be completed, this issue should be marked as blocked. If the issue is no longer needed, it should be labeled as such and then closed.

**Tasks**
- [ ] Validate Security Gap Still Exists
- [ ] Define/Refine Playbook
- [ ] Validate Data Visibility/Usability 
- [ ] Gather and Analyze Data According to the Playbook 
- [ ] Automate Steps As You Can/Go
- [ ] Update the Playbooks
- [ ] Write Report
- [ ] Share Findings
- [ ] Close Issue

**Note:** Incidents should be escalated as they are found.
